//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/VivaActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VivaActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VivaActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VivaActions"",
    ""maps"": [
        {
            ""name"": ""desktop"",
            ""id"": ""c7fc6f0f-dd49-4217-b1fd-ae9555612a0e"",
            ""actions"": [
                {
                    ""name"": ""A"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5bafe1fd-9d40-4377-8843-b47b33314573"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8edc6da9-b1e3-4791-bd29-a50ecfae35ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""C"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d984a7c9-2312-477e-a5eb-e2301bc77e5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b04dcaec-ecc3-47ea-bf64-33ee16b847a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""E"",
                    ""type"": ""PassThrough"",
                    ""id"": ""73b900c5-2ad3-4986-b9fe-ef52747364b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F"",
                    ""type"": ""PassThrough"",
                    ""id"": ""84975461-b291-4e3b-bf53-8db3c842b377"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""G"",
                    ""type"": ""PassThrough"",
                    ""id"": ""982c71f2-9a50-419b-a98d-bca34cd8fe58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""H"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ba97475a-da81-40ba-a4c3-1f757a7eab34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""I"",
                    ""type"": ""PassThrough"",
                    ""id"": ""560d3d30-d036-4b16-bcda-383275b56102"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""J"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b19f3a1b-e606-4b18-88f4-9896531d6574"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""K"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ba4e7d92-8e5a-471c-869e-20abefb17ec9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c62712ca-e406-407d-98bb-9e2ea4775e1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""M"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cdc65e0e-cb1f-4c5d-9040-a232573dc055"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""N"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d34b6903-664e-443a-ab1d-8f0aee9c94bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""O"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5c38aaa0-09b5-4b59-9ba4-53d00bef96d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P"",
                    ""type"": ""PassThrough"",
                    ""id"": ""57736e75-c218-4e2a-b023-d729af2466cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Q"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a97d21b3-66c8-4ad1-9914-34e2eec9f1c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cd1079c8-c5f0-41d3-ac00-016d4cad2996"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""S"",
                    ""type"": ""PassThrough"",
                    ""id"": ""41fa8d24-b72a-4047-8edf-0f15a132e2a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""T"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a9b933ce-8b87-4947-826e-fe133bc0bade"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""U"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a8399239-d944-438f-a528-bd2a49e5f5d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""V"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c8a91b72-e002-4309-a09b-b5e8301c9225"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""W"",
                    ""type"": ""PassThrough"",
                    ""id"": ""21aca9b7-6da3-49b8-9724-6d3b03e56fa0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7bd89d6d-759f-42a7-96de-4e5896446188"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""PassThrough"",
                    ""id"": ""091ff3f2-05ab-4eb1-a018-5ba1af615f19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Z"",
                    ""type"": ""PassThrough"",
                    ""id"": ""151a8204-bdf2-4e43-ba2e-d090d0824286"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tab"",
                    ""type"": ""PassThrough"",
                    ""id"": ""054c4752-e7b8-490f-9664-2c8823119dfb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e8d35062-b11d-4c97-bbee-23d9221e59e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleMouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""52c57d1f-7b78-4d9a-85ae-92202e4ac760"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1fceb422-7dd7-45eb-b8cb-7ca6f9958d4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""237cbde4-f81b-4ddf-a726-b47664ad56a3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""4c8a03af-bdaa-4f6a-ab95-b3b2890979e9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftShift"",
                    ""type"": ""PassThrough"",
                    ""id"": ""434f4558-300c-4df4-b484-7db4facca4ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4ed4778d-4886-474b-832b-7eadcb135bb5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Space"",
                    ""type"": ""PassThrough"",
                    ""id"": ""348aa025-c3c8-4627-800e-0f0a7fcf93a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""4535b9fd-82c5-484c-8970-fbb83da39940"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftControl"",
                    ""type"": ""Button"",
                    ""id"": ""f84bd637-8254-4bfc-9ad7-ddece09c3ac4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5fa97519-d400-4bbd-87de-e9988c1431ad"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73fa4565-abc6-48c3-adf8-0ee6361f0320"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a76ff58-6d80-487b-b3b0-24963b34a286"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0ee03d3-731d-490e-a849-52f82b0438c3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5a697ce-e162-4955-abd1-b5349c467586"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa022d99-6636-4653-ad9f-0733f311441f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3c518cd-2e87-4c81-8f08-643be8964545"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb94efbc-799b-4fef-8fc3-12bb66814a53"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""H"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b2868b9-66a7-454c-bb4d-037474241431"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""I"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73efb7dd-5cc4-47a8-af19-1fceb0030960"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""K"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2adce45b-6308-4301-9dbc-fae7eb776019"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3350ae35-0147-4d73-bc20-66e848510639"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""M"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ace9f152-835b-4994-9ec1-1ef9f875cd1a"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""N"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c229aa52-8d45-47e6-b650-42fca1b4593d"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""O"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34a688a8-c209-47c9-8b34-c7d9582a9bfd"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b30defa3-872d-4f2f-95f8-de98e62fa8fb"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5774f5a1-01ae-45c0-ab2d-32ceaf3707cb"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59ac95eb-97d9-4c4a-b22b-825a7272eaf6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""S"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21f7cec8-e529-4d44-8b36-3ec37135d09a"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""T"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59be7ab3-0115-4a18-887f-8386edf6d645"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""U"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""588188a5-5e98-41fa-a9d9-f008a1a886db"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""V"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b5a07e0-31b7-4cd5-a525-8f912b87ba47"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""W"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caff4bf9-d0fd-49f9-bdf8-66a992567834"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4b60bf2-b0b4-4ed3-baa3-1aa0dfa6d4a8"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca529d57-827a-447f-88cc-d146eeccbb71"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Z"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7715fcb6-c995-46c1-b8ff-4647460dce6a"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""J"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f24bf5e2-8a15-4a67-8736-0cb69886c0f8"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac086980-442f-45eb-a8de-cc9655a106d4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5470950-1341-461b-9748-93692ca2dc6b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c8cdc5f-b60d-457b-b91f-c5bd89de8d44"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5955334-2071-48d4-9584-e821d38d4ca8"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df38abe6-ab26-408a-b451-0f6a38a16170"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftShift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1211288-b7e1-4f9d-b148-c281b0c3a0c1"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07218c85-aa6d-4ce1-87f7-06ba2d47a982"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cbd81a7-5b92-4172-ab46-2f04afe64618"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9973581-8d1e-45d1-bb1e-cb729eb54da6"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""350971d5-71e8-4d05-8439-6bf9c7367db8"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiddleMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""vrControls"",
            ""id"": ""bf1af3e4-639c-4e5d-993b-9b357777dcaf"",
            ""actions"": [
                {
                    ""name"": ""leftAnalogPos"",
                    ""type"": ""Value"",
                    ""id"": ""5b312d5f-3768-471b-9a2c-f0aae78cad50"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rightAnalogPos"",
                    ""type"": ""Value"",
                    ""id"": ""de1a131d-d027-44a3-b0b2-90731b306c0a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""leftTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""fc92a3f4-1e5d-4286-aabe-f1d6e6c38b3e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rightTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""7d978292-9c6a-4385-9d31-39f754d52236"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""centerEyePos"",
                    ""type"": ""Value"",
                    ""id"": ""2aa9410c-02c8-4d09-8395-a7a23073938e"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""centerEyeRot"",
                    ""type"": ""Value"",
                    ""id"": ""5fa8dd5d-0361-4687-a87b-8b12d673b98a"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rightHandPos"",
                    ""type"": ""Value"",
                    ""id"": ""224adb44-ebaf-4d0b-8f8d-9fa40fb5b12e"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rightHandRot"",
                    ""type"": ""Value"",
                    ""id"": ""e1249a32-3206-45b4-8196-fc9ef047f07d"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""leftHandPos"",
                    ""type"": ""Value"",
                    ""id"": ""d4020249-6270-4605-84a3-d0745e4b0a37"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""leftHandRot"",
                    ""type"": ""Value"",
                    ""id"": ""c4bfe92b-4999-4cf5-87df-1c174358fade"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""leftTriggerClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""704f76aa-ddf9-42fb-a79a-31acef263f0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rightTriggerClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dc9d17b6-c03e-468d-8978-8ddf49cd8250"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rightButtonA"",
                    ""type"": ""Button"",
                    ""id"": ""abfd4b54-234f-4fc2-af0f-b8b60acce25d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""leftButtonA"",
                    ""type"": ""Button"",
                    ""id"": ""16b741e2-a6ba-40ac-ad82-82679b5f251a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rightButtonB"",
                    ""type"": ""Button"",
                    ""id"": ""21112070-98c5-479c-84dd-80de3fb9df81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""leftButtonB"",
                    ""type"": ""Button"",
                    ""id"": ""b91a651a-9962-42e2-bdd0-86be0de26f41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rightGrip"",
                    ""type"": ""Value"",
                    ""id"": ""64da4e95-bf76-4f8e-a096-1e30706eb117"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""leftGrip"",
                    ""type"": ""Value"",
                    ""id"": ""f4f55014-9e96-4c94-9078-0bff13919f65"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rightHandPose"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8986f488-3de0-4115-a278-e615e3a5d312"",
                    ""expectedControlType"": ""Pose"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""leftHandPose"",
                    ""type"": ""PassThrough"",
                    ""id"": ""555d2761-c9b6-45d5-ace4-eeeb1fdfb4df"",
                    ""expectedControlType"": ""Pose"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2e72cda9-e63b-47d2-b196-7fe052d5beee"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftAnalogPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""477bd884-6357-4fc1-b255-350c4186dea1"",
                    ""path"": ""<XRController>{LeftHand}/touchpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftAnalogPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0068ad26-07d2-48db-830e-b1ac59bc3e7e"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightAnalogPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4a9ddca-7a59-4d8e-9b4b-2b3ee001c58b"",
                    ""path"": ""<XRController>{RightHand}/touchpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightAnalogPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""826bff6b-3caa-4903-8953-acaf3a546c00"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6185b327-18a8-4fb1-a290-b096a726002c"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43635260-4b0c-4dda-9bae-49b1aaf1eb3f"",
                    ""path"": ""<XRHMD>/centerEyePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""centerEyePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55832a6b-e3ca-402c-a6fd-689c49547916"",
                    ""path"": ""<XRHMD>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""centerEyeRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c74b5413-398b-4eaf-9f1e-2c0636fecf80"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightHandRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1894d25-64b0-4991-a716-03c74e34939c"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightHandPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a4f9e69-59f7-48c6-9418-4a604eef1a9d"",
                    ""path"": ""<XRController>{LeftHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftHandRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f09d19dc-1040-4e47-a004-4444a42298b1"",
                    ""path"": ""<XRController>{LeftHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftHandPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5cdddbb-6660-4692-863b-89d7acfca6bc"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftTriggerClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7e4c511-32fa-4885-8f93-4373dfcecfd2"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightTriggerClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69ca1efb-2eb1-4c78-9f01-7daa6c2f33cb"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightButtonA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f665ea4d-93aa-4473-96c5-a9eac93b48ae"",
                    ""path"": ""<ViveController>{RightHand}/trackpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightButtonA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47aee80a-c728-43f0-943e-ab389beff8a1"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightButtonB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aac85253-2ff2-4519-a802-e47a4fe0699f"",
                    ""path"": ""<XRController>{RightHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightButtonB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ce49a81-c7fb-4472-bac2-3757c8e24a24"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftButtonB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f62f6d5-b014-4e2e-9580-88d381e0bdcd"",
                    ""path"": ""<XRController>{LeftHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftButtonB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e7c652c-d048-4d4c-a6ae-b0830fb3efd1"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftButtonA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8703f87-90d0-4b58-974b-ee335b958ab5"",
                    ""path"": ""<ViveController>{LeftHand}/trackpadClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftButtonA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86128f16-bb0d-4c77-a9cf-1d65789d3105"",
                    ""path"": ""<XRController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c4f2eb8-7b47-4f0d-ac32-63e79e50b7e0"",
                    ""path"": ""<XRController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftGrip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87cd49fa-fc60-4c65-a76a-826c6dbc1e72"",
                    ""path"": ""<XRController>{RightHand}/devicePose"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightHandPose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d6fb5a2-e440-47d7-b2bb-3d06c6d50dc8"",
                    ""path"": ""<XRController>{LeftHand}/devicePose"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftHandPose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // desktop
        m_desktop = asset.FindActionMap("desktop", throwIfNotFound: true);
        m_desktop_A = m_desktop.FindAction("A", throwIfNotFound: true);
        m_desktop_B = m_desktop.FindAction("B", throwIfNotFound: true);
        m_desktop_C = m_desktop.FindAction("C", throwIfNotFound: true);
        m_desktop_D = m_desktop.FindAction("D", throwIfNotFound: true);
        m_desktop_E = m_desktop.FindAction("E", throwIfNotFound: true);
        m_desktop_F = m_desktop.FindAction("F", throwIfNotFound: true);
        m_desktop_G = m_desktop.FindAction("G", throwIfNotFound: true);
        m_desktop_H = m_desktop.FindAction("H", throwIfNotFound: true);
        m_desktop_I = m_desktop.FindAction("I", throwIfNotFound: true);
        m_desktop_J = m_desktop.FindAction("J", throwIfNotFound: true);
        m_desktop_K = m_desktop.FindAction("K", throwIfNotFound: true);
        m_desktop_L = m_desktop.FindAction("L", throwIfNotFound: true);
        m_desktop_M = m_desktop.FindAction("M", throwIfNotFound: true);
        m_desktop_N = m_desktop.FindAction("N", throwIfNotFound: true);
        m_desktop_O = m_desktop.FindAction("O", throwIfNotFound: true);
        m_desktop_P = m_desktop.FindAction("P", throwIfNotFound: true);
        m_desktop_Q = m_desktop.FindAction("Q", throwIfNotFound: true);
        m_desktop_R = m_desktop.FindAction("R", throwIfNotFound: true);
        m_desktop_S = m_desktop.FindAction("S", throwIfNotFound: true);
        m_desktop_T = m_desktop.FindAction("T", throwIfNotFound: true);
        m_desktop_U = m_desktop.FindAction("U", throwIfNotFound: true);
        m_desktop_V = m_desktop.FindAction("V", throwIfNotFound: true);
        m_desktop_W = m_desktop.FindAction("W", throwIfNotFound: true);
        m_desktop_X = m_desktop.FindAction("X", throwIfNotFound: true);
        m_desktop_Y = m_desktop.FindAction("Y", throwIfNotFound: true);
        m_desktop_Z = m_desktop.FindAction("Z", throwIfNotFound: true);
        m_desktop_Tab = m_desktop.FindAction("Tab", throwIfNotFound: true);
        m_desktop_RightMouse = m_desktop.FindAction("RightMouse", throwIfNotFound: true);
        m_desktop_MiddleMouse = m_desktop.FindAction("MiddleMouse", throwIfNotFound: true);
        m_desktop_LeftMouse = m_desktop.FindAction("LeftMouse", throwIfNotFound: true);
        m_desktop_MousePosition = m_desktop.FindAction("MousePosition", throwIfNotFound: true);
        m_desktop_MouseVelocity = m_desktop.FindAction("MouseVelocity", throwIfNotFound: true);
        m_desktop_LeftShift = m_desktop.FindAction("LeftShift", throwIfNotFound: true);
        m_desktop_Scroll = m_desktop.FindAction("Scroll", throwIfNotFound: true);
        m_desktop_Space = m_desktop.FindAction("Space", throwIfNotFound: true);
        m_desktop_Esc = m_desktop.FindAction("Esc", throwIfNotFound: true);
        m_desktop_LeftControl = m_desktop.FindAction("LeftControl", throwIfNotFound: true);
        // vrControls
        m_vrControls = asset.FindActionMap("vrControls", throwIfNotFound: true);
        m_vrControls_leftAnalogPos = m_vrControls.FindAction("leftAnalogPos", throwIfNotFound: true);
        m_vrControls_rightAnalogPos = m_vrControls.FindAction("rightAnalogPos", throwIfNotFound: true);
        m_vrControls_leftTrigger = m_vrControls.FindAction("leftTrigger", throwIfNotFound: true);
        m_vrControls_rightTrigger = m_vrControls.FindAction("rightTrigger", throwIfNotFound: true);
        m_vrControls_centerEyePos = m_vrControls.FindAction("centerEyePos", throwIfNotFound: true);
        m_vrControls_centerEyeRot = m_vrControls.FindAction("centerEyeRot", throwIfNotFound: true);
        m_vrControls_rightHandPos = m_vrControls.FindAction("rightHandPos", throwIfNotFound: true);
        m_vrControls_rightHandRot = m_vrControls.FindAction("rightHandRot", throwIfNotFound: true);
        m_vrControls_leftHandPos = m_vrControls.FindAction("leftHandPos", throwIfNotFound: true);
        m_vrControls_leftHandRot = m_vrControls.FindAction("leftHandRot", throwIfNotFound: true);
        m_vrControls_leftTriggerClick = m_vrControls.FindAction("leftTriggerClick", throwIfNotFound: true);
        m_vrControls_rightTriggerClick = m_vrControls.FindAction("rightTriggerClick", throwIfNotFound: true);
        m_vrControls_rightButtonA = m_vrControls.FindAction("rightButtonA", throwIfNotFound: true);
        m_vrControls_leftButtonA = m_vrControls.FindAction("leftButtonA", throwIfNotFound: true);
        m_vrControls_rightButtonB = m_vrControls.FindAction("rightButtonB", throwIfNotFound: true);
        m_vrControls_leftButtonB = m_vrControls.FindAction("leftButtonB", throwIfNotFound: true);
        m_vrControls_rightGrip = m_vrControls.FindAction("rightGrip", throwIfNotFound: true);
        m_vrControls_leftGrip = m_vrControls.FindAction("leftGrip", throwIfNotFound: true);
        m_vrControls_rightHandPose = m_vrControls.FindAction("rightHandPose", throwIfNotFound: true);
        m_vrControls_leftHandPose = m_vrControls.FindAction("leftHandPose", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // desktop
    private readonly InputActionMap m_desktop;
    private IDesktopActions m_DesktopActionsCallbackInterface;
    private readonly InputAction m_desktop_A;
    private readonly InputAction m_desktop_B;
    private readonly InputAction m_desktop_C;
    private readonly InputAction m_desktop_D;
    private readonly InputAction m_desktop_E;
    private readonly InputAction m_desktop_F;
    private readonly InputAction m_desktop_G;
    private readonly InputAction m_desktop_H;
    private readonly InputAction m_desktop_I;
    private readonly InputAction m_desktop_J;
    private readonly InputAction m_desktop_K;
    private readonly InputAction m_desktop_L;
    private readonly InputAction m_desktop_M;
    private readonly InputAction m_desktop_N;
    private readonly InputAction m_desktop_O;
    private readonly InputAction m_desktop_P;
    private readonly InputAction m_desktop_Q;
    private readonly InputAction m_desktop_R;
    private readonly InputAction m_desktop_S;
    private readonly InputAction m_desktop_T;
    private readonly InputAction m_desktop_U;
    private readonly InputAction m_desktop_V;
    private readonly InputAction m_desktop_W;
    private readonly InputAction m_desktop_X;
    private readonly InputAction m_desktop_Y;
    private readonly InputAction m_desktop_Z;
    private readonly InputAction m_desktop_Tab;
    private readonly InputAction m_desktop_RightMouse;
    private readonly InputAction m_desktop_MiddleMouse;
    private readonly InputAction m_desktop_LeftMouse;
    private readonly InputAction m_desktop_MousePosition;
    private readonly InputAction m_desktop_MouseVelocity;
    private readonly InputAction m_desktop_LeftShift;
    private readonly InputAction m_desktop_Scroll;
    private readonly InputAction m_desktop_Space;
    private readonly InputAction m_desktop_Esc;
    private readonly InputAction m_desktop_LeftControl;
    public struct DesktopActions
    {
        private @VivaActions m_Wrapper;
        public DesktopActions(@VivaActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @A => m_Wrapper.m_desktop_A;
        public InputAction @B => m_Wrapper.m_desktop_B;
        public InputAction @C => m_Wrapper.m_desktop_C;
        public InputAction @D => m_Wrapper.m_desktop_D;
        public InputAction @E => m_Wrapper.m_desktop_E;
        public InputAction @F => m_Wrapper.m_desktop_F;
        public InputAction @G => m_Wrapper.m_desktop_G;
        public InputAction @H => m_Wrapper.m_desktop_H;
        public InputAction @I => m_Wrapper.m_desktop_I;
        public InputAction @J => m_Wrapper.m_desktop_J;
        public InputAction @K => m_Wrapper.m_desktop_K;
        public InputAction @L => m_Wrapper.m_desktop_L;
        public InputAction @M => m_Wrapper.m_desktop_M;
        public InputAction @N => m_Wrapper.m_desktop_N;
        public InputAction @O => m_Wrapper.m_desktop_O;
        public InputAction @P => m_Wrapper.m_desktop_P;
        public InputAction @Q => m_Wrapper.m_desktop_Q;
        public InputAction @R => m_Wrapper.m_desktop_R;
        public InputAction @S => m_Wrapper.m_desktop_S;
        public InputAction @T => m_Wrapper.m_desktop_T;
        public InputAction @U => m_Wrapper.m_desktop_U;
        public InputAction @V => m_Wrapper.m_desktop_V;
        public InputAction @W => m_Wrapper.m_desktop_W;
        public InputAction @X => m_Wrapper.m_desktop_X;
        public InputAction @Y => m_Wrapper.m_desktop_Y;
        public InputAction @Z => m_Wrapper.m_desktop_Z;
        public InputAction @Tab => m_Wrapper.m_desktop_Tab;
        public InputAction @RightMouse => m_Wrapper.m_desktop_RightMouse;
        public InputAction @MiddleMouse => m_Wrapper.m_desktop_MiddleMouse;
        public InputAction @LeftMouse => m_Wrapper.m_desktop_LeftMouse;
        public InputAction @MousePosition => m_Wrapper.m_desktop_MousePosition;
        public InputAction @MouseVelocity => m_Wrapper.m_desktop_MouseVelocity;
        public InputAction @LeftShift => m_Wrapper.m_desktop_LeftShift;
        public InputAction @Scroll => m_Wrapper.m_desktop_Scroll;
        public InputAction @Space => m_Wrapper.m_desktop_Space;
        public InputAction @Esc => m_Wrapper.m_desktop_Esc;
        public InputAction @LeftControl => m_Wrapper.m_desktop_LeftControl;
        public InputActionMap Get() { return m_Wrapper.m_desktop; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DesktopActions set) { return set.Get(); }
        public void SetCallbacks(IDesktopActions instance)
        {
            if (m_Wrapper.m_DesktopActionsCallbackInterface != null)
            {
                @A.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnA;
                @B.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnB;
                @B.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnB;
                @B.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnB;
                @C.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnC;
                @C.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnC;
                @C.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnC;
                @D.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnD;
                @D.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnD;
                @D.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnD;
                @E.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnE;
                @E.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnE;
                @E.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnE;
                @F.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnF;
                @F.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnF;
                @F.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnF;
                @G.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnG;
                @G.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnG;
                @G.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnG;
                @H.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnH;
                @H.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnH;
                @H.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnH;
                @I.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnI;
                @I.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnI;
                @I.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnI;
                @J.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnJ;
                @J.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnJ;
                @J.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnJ;
                @K.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnK;
                @K.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnK;
                @K.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnK;
                @L.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnL;
                @L.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnL;
                @L.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnL;
                @M.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnM;
                @M.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnM;
                @M.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnM;
                @N.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnN;
                @N.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnN;
                @N.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnN;
                @O.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnO;
                @O.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnO;
                @O.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnO;
                @P.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnP;
                @P.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnP;
                @P.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnP;
                @Q.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnQ;
                @Q.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnQ;
                @Q.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnQ;
                @R.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnR;
                @R.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnR;
                @R.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnR;
                @S.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnS;
                @S.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnS;
                @S.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnS;
                @T.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnT;
                @T.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnT;
                @T.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnT;
                @U.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnU;
                @U.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnU;
                @U.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnU;
                @V.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnV;
                @V.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnV;
                @V.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnV;
                @W.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnW;
                @W.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnW;
                @W.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnW;
                @X.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnX;
                @Y.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnY;
                @Y.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnY;
                @Y.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnY;
                @Z.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnZ;
                @Z.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnZ;
                @Z.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnZ;
                @Tab.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnTab;
                @Tab.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnTab;
                @Tab.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnTab;
                @RightMouse.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnRightMouse;
                @RightMouse.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnRightMouse;
                @RightMouse.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnRightMouse;
                @MiddleMouse.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnMiddleMouse;
                @MiddleMouse.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnMiddleMouse;
                @MiddleMouse.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnMiddleMouse;
                @LeftMouse.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnLeftMouse;
                @LeftMouse.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnLeftMouse;
                @LeftMouse.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnLeftMouse;
                @MousePosition.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnMousePosition;
                @MouseVelocity.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnMouseVelocity;
                @MouseVelocity.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnMouseVelocity;
                @MouseVelocity.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnMouseVelocity;
                @LeftShift.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnLeftShift;
                @LeftShift.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnLeftShift;
                @LeftShift.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnLeftShift;
                @Scroll.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnScroll;
                @Scroll.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnScroll;
                @Scroll.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnScroll;
                @Space.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnSpace;
                @Space.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnSpace;
                @Space.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnSpace;
                @Esc.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnEsc;
                @Esc.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnEsc;
                @Esc.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnEsc;
                @LeftControl.started -= m_Wrapper.m_DesktopActionsCallbackInterface.OnLeftControl;
                @LeftControl.performed -= m_Wrapper.m_DesktopActionsCallbackInterface.OnLeftControl;
                @LeftControl.canceled -= m_Wrapper.m_DesktopActionsCallbackInterface.OnLeftControl;
            }
            m_Wrapper.m_DesktopActionsCallbackInterface = instance;
            if (instance != null)
            {
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
                @C.started += instance.OnC;
                @C.performed += instance.OnC;
                @C.canceled += instance.OnC;
                @D.started += instance.OnD;
                @D.performed += instance.OnD;
                @D.canceled += instance.OnD;
                @E.started += instance.OnE;
                @E.performed += instance.OnE;
                @E.canceled += instance.OnE;
                @F.started += instance.OnF;
                @F.performed += instance.OnF;
                @F.canceled += instance.OnF;
                @G.started += instance.OnG;
                @G.performed += instance.OnG;
                @G.canceled += instance.OnG;
                @H.started += instance.OnH;
                @H.performed += instance.OnH;
                @H.canceled += instance.OnH;
                @I.started += instance.OnI;
                @I.performed += instance.OnI;
                @I.canceled += instance.OnI;
                @J.started += instance.OnJ;
                @J.performed += instance.OnJ;
                @J.canceled += instance.OnJ;
                @K.started += instance.OnK;
                @K.performed += instance.OnK;
                @K.canceled += instance.OnK;
                @L.started += instance.OnL;
                @L.performed += instance.OnL;
                @L.canceled += instance.OnL;
                @M.started += instance.OnM;
                @M.performed += instance.OnM;
                @M.canceled += instance.OnM;
                @N.started += instance.OnN;
                @N.performed += instance.OnN;
                @N.canceled += instance.OnN;
                @O.started += instance.OnO;
                @O.performed += instance.OnO;
                @O.canceled += instance.OnO;
                @P.started += instance.OnP;
                @P.performed += instance.OnP;
                @P.canceled += instance.OnP;
                @Q.started += instance.OnQ;
                @Q.performed += instance.OnQ;
                @Q.canceled += instance.OnQ;
                @R.started += instance.OnR;
                @R.performed += instance.OnR;
                @R.canceled += instance.OnR;
                @S.started += instance.OnS;
                @S.performed += instance.OnS;
                @S.canceled += instance.OnS;
                @T.started += instance.OnT;
                @T.performed += instance.OnT;
                @T.canceled += instance.OnT;
                @U.started += instance.OnU;
                @U.performed += instance.OnU;
                @U.canceled += instance.OnU;
                @V.started += instance.OnV;
                @V.performed += instance.OnV;
                @V.canceled += instance.OnV;
                @W.started += instance.OnW;
                @W.performed += instance.OnW;
                @W.canceled += instance.OnW;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @Y.started += instance.OnY;
                @Y.performed += instance.OnY;
                @Y.canceled += instance.OnY;
                @Z.started += instance.OnZ;
                @Z.performed += instance.OnZ;
                @Z.canceled += instance.OnZ;
                @Tab.started += instance.OnTab;
                @Tab.performed += instance.OnTab;
                @Tab.canceled += instance.OnTab;
                @RightMouse.started += instance.OnRightMouse;
                @RightMouse.performed += instance.OnRightMouse;
                @RightMouse.canceled += instance.OnRightMouse;
                @MiddleMouse.started += instance.OnMiddleMouse;
                @MiddleMouse.performed += instance.OnMiddleMouse;
                @MiddleMouse.canceled += instance.OnMiddleMouse;
                @LeftMouse.started += instance.OnLeftMouse;
                @LeftMouse.performed += instance.OnLeftMouse;
                @LeftMouse.canceled += instance.OnLeftMouse;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @MouseVelocity.started += instance.OnMouseVelocity;
                @MouseVelocity.performed += instance.OnMouseVelocity;
                @MouseVelocity.canceled += instance.OnMouseVelocity;
                @LeftShift.started += instance.OnLeftShift;
                @LeftShift.performed += instance.OnLeftShift;
                @LeftShift.canceled += instance.OnLeftShift;
                @Scroll.started += instance.OnScroll;
                @Scroll.performed += instance.OnScroll;
                @Scroll.canceled += instance.OnScroll;
                @Space.started += instance.OnSpace;
                @Space.performed += instance.OnSpace;
                @Space.canceled += instance.OnSpace;
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
                @LeftControl.started += instance.OnLeftControl;
                @LeftControl.performed += instance.OnLeftControl;
                @LeftControl.canceled += instance.OnLeftControl;
            }
        }
    }
    public DesktopActions @desktop => new DesktopActions(this);

    // vrControls
    private readonly InputActionMap m_vrControls;
    private IVrControlsActions m_VrControlsActionsCallbackInterface;
    private readonly InputAction m_vrControls_leftAnalogPos;
    private readonly InputAction m_vrControls_rightAnalogPos;
    private readonly InputAction m_vrControls_leftTrigger;
    private readonly InputAction m_vrControls_rightTrigger;
    private readonly InputAction m_vrControls_centerEyePos;
    private readonly InputAction m_vrControls_centerEyeRot;
    private readonly InputAction m_vrControls_rightHandPos;
    private readonly InputAction m_vrControls_rightHandRot;
    private readonly InputAction m_vrControls_leftHandPos;
    private readonly InputAction m_vrControls_leftHandRot;
    private readonly InputAction m_vrControls_leftTriggerClick;
    private readonly InputAction m_vrControls_rightTriggerClick;
    private readonly InputAction m_vrControls_rightButtonA;
    private readonly InputAction m_vrControls_leftButtonA;
    private readonly InputAction m_vrControls_rightButtonB;
    private readonly InputAction m_vrControls_leftButtonB;
    private readonly InputAction m_vrControls_rightGrip;
    private readonly InputAction m_vrControls_leftGrip;
    private readonly InputAction m_vrControls_rightHandPose;
    private readonly InputAction m_vrControls_leftHandPose;
    public struct VrControlsActions
    {
        private @VivaActions m_Wrapper;
        public VrControlsActions(@VivaActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @leftAnalogPos => m_Wrapper.m_vrControls_leftAnalogPos;
        public InputAction @rightAnalogPos => m_Wrapper.m_vrControls_rightAnalogPos;
        public InputAction @leftTrigger => m_Wrapper.m_vrControls_leftTrigger;
        public InputAction @rightTrigger => m_Wrapper.m_vrControls_rightTrigger;
        public InputAction @centerEyePos => m_Wrapper.m_vrControls_centerEyePos;
        public InputAction @centerEyeRot => m_Wrapper.m_vrControls_centerEyeRot;
        public InputAction @rightHandPos => m_Wrapper.m_vrControls_rightHandPos;
        public InputAction @rightHandRot => m_Wrapper.m_vrControls_rightHandRot;
        public InputAction @leftHandPos => m_Wrapper.m_vrControls_leftHandPos;
        public InputAction @leftHandRot => m_Wrapper.m_vrControls_leftHandRot;
        public InputAction @leftTriggerClick => m_Wrapper.m_vrControls_leftTriggerClick;
        public InputAction @rightTriggerClick => m_Wrapper.m_vrControls_rightTriggerClick;
        public InputAction @rightButtonA => m_Wrapper.m_vrControls_rightButtonA;
        public InputAction @leftButtonA => m_Wrapper.m_vrControls_leftButtonA;
        public InputAction @rightButtonB => m_Wrapper.m_vrControls_rightButtonB;
        public InputAction @leftButtonB => m_Wrapper.m_vrControls_leftButtonB;
        public InputAction @rightGrip => m_Wrapper.m_vrControls_rightGrip;
        public InputAction @leftGrip => m_Wrapper.m_vrControls_leftGrip;
        public InputAction @rightHandPose => m_Wrapper.m_vrControls_rightHandPose;
        public InputAction @leftHandPose => m_Wrapper.m_vrControls_leftHandPose;
        public InputActionMap Get() { return m_Wrapper.m_vrControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VrControlsActions set) { return set.Get(); }
        public void SetCallbacks(IVrControlsActions instance)
        {
            if (m_Wrapper.m_VrControlsActionsCallbackInterface != null)
            {
                @leftAnalogPos.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftAnalogPos;
                @leftAnalogPos.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftAnalogPos;
                @leftAnalogPos.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftAnalogPos;
                @rightAnalogPos.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightAnalogPos;
                @rightAnalogPos.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightAnalogPos;
                @rightAnalogPos.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightAnalogPos;
                @leftTrigger.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftTrigger;
                @leftTrigger.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftTrigger;
                @leftTrigger.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftTrigger;
                @rightTrigger.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightTrigger;
                @rightTrigger.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightTrigger;
                @rightTrigger.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightTrigger;
                @centerEyePos.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnCenterEyePos;
                @centerEyePos.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnCenterEyePos;
                @centerEyePos.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnCenterEyePos;
                @centerEyeRot.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnCenterEyeRot;
                @centerEyeRot.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnCenterEyeRot;
                @centerEyeRot.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnCenterEyeRot;
                @rightHandPos.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightHandPos;
                @rightHandPos.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightHandPos;
                @rightHandPos.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightHandPos;
                @rightHandRot.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightHandRot;
                @rightHandRot.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightHandRot;
                @rightHandRot.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightHandRot;
                @leftHandPos.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftHandPos;
                @leftHandPos.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftHandPos;
                @leftHandPos.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftHandPos;
                @leftHandRot.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftHandRot;
                @leftHandRot.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftHandRot;
                @leftHandRot.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftHandRot;
                @leftTriggerClick.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftTriggerClick;
                @leftTriggerClick.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftTriggerClick;
                @leftTriggerClick.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftTriggerClick;
                @rightTriggerClick.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightTriggerClick;
                @rightTriggerClick.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightTriggerClick;
                @rightTriggerClick.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightTriggerClick;
                @rightButtonA.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightButtonA;
                @rightButtonA.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightButtonA;
                @rightButtonA.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightButtonA;
                @leftButtonA.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftButtonA;
                @leftButtonA.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftButtonA;
                @leftButtonA.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftButtonA;
                @rightButtonB.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightButtonB;
                @rightButtonB.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightButtonB;
                @rightButtonB.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightButtonB;
                @leftButtonB.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftButtonB;
                @leftButtonB.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftButtonB;
                @leftButtonB.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftButtonB;
                @rightGrip.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightGrip;
                @rightGrip.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightGrip;
                @rightGrip.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightGrip;
                @leftGrip.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftGrip;
                @leftGrip.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftGrip;
                @leftGrip.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftGrip;
                @rightHandPose.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightHandPose;
                @rightHandPose.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightHandPose;
                @rightHandPose.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnRightHandPose;
                @leftHandPose.started -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftHandPose;
                @leftHandPose.performed -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftHandPose;
                @leftHandPose.canceled -= m_Wrapper.m_VrControlsActionsCallbackInterface.OnLeftHandPose;
            }
            m_Wrapper.m_VrControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @leftAnalogPos.started += instance.OnLeftAnalogPos;
                @leftAnalogPos.performed += instance.OnLeftAnalogPos;
                @leftAnalogPos.canceled += instance.OnLeftAnalogPos;
                @rightAnalogPos.started += instance.OnRightAnalogPos;
                @rightAnalogPos.performed += instance.OnRightAnalogPos;
                @rightAnalogPos.canceled += instance.OnRightAnalogPos;
                @leftTrigger.started += instance.OnLeftTrigger;
                @leftTrigger.performed += instance.OnLeftTrigger;
                @leftTrigger.canceled += instance.OnLeftTrigger;
                @rightTrigger.started += instance.OnRightTrigger;
                @rightTrigger.performed += instance.OnRightTrigger;
                @rightTrigger.canceled += instance.OnRightTrigger;
                @centerEyePos.started += instance.OnCenterEyePos;
                @centerEyePos.performed += instance.OnCenterEyePos;
                @centerEyePos.canceled += instance.OnCenterEyePos;
                @centerEyeRot.started += instance.OnCenterEyeRot;
                @centerEyeRot.performed += instance.OnCenterEyeRot;
                @centerEyeRot.canceled += instance.OnCenterEyeRot;
                @rightHandPos.started += instance.OnRightHandPos;
                @rightHandPos.performed += instance.OnRightHandPos;
                @rightHandPos.canceled += instance.OnRightHandPos;
                @rightHandRot.started += instance.OnRightHandRot;
                @rightHandRot.performed += instance.OnRightHandRot;
                @rightHandRot.canceled += instance.OnRightHandRot;
                @leftHandPos.started += instance.OnLeftHandPos;
                @leftHandPos.performed += instance.OnLeftHandPos;
                @leftHandPos.canceled += instance.OnLeftHandPos;
                @leftHandRot.started += instance.OnLeftHandRot;
                @leftHandRot.performed += instance.OnLeftHandRot;
                @leftHandRot.canceled += instance.OnLeftHandRot;
                @leftTriggerClick.started += instance.OnLeftTriggerClick;
                @leftTriggerClick.performed += instance.OnLeftTriggerClick;
                @leftTriggerClick.canceled += instance.OnLeftTriggerClick;
                @rightTriggerClick.started += instance.OnRightTriggerClick;
                @rightTriggerClick.performed += instance.OnRightTriggerClick;
                @rightTriggerClick.canceled += instance.OnRightTriggerClick;
                @rightButtonA.started += instance.OnRightButtonA;
                @rightButtonA.performed += instance.OnRightButtonA;
                @rightButtonA.canceled += instance.OnRightButtonA;
                @leftButtonA.started += instance.OnLeftButtonA;
                @leftButtonA.performed += instance.OnLeftButtonA;
                @leftButtonA.canceled += instance.OnLeftButtonA;
                @rightButtonB.started += instance.OnRightButtonB;
                @rightButtonB.performed += instance.OnRightButtonB;
                @rightButtonB.canceled += instance.OnRightButtonB;
                @leftButtonB.started += instance.OnLeftButtonB;
                @leftButtonB.performed += instance.OnLeftButtonB;
                @leftButtonB.canceled += instance.OnLeftButtonB;
                @rightGrip.started += instance.OnRightGrip;
                @rightGrip.performed += instance.OnRightGrip;
                @rightGrip.canceled += instance.OnRightGrip;
                @leftGrip.started += instance.OnLeftGrip;
                @leftGrip.performed += instance.OnLeftGrip;
                @leftGrip.canceled += instance.OnLeftGrip;
                @rightHandPose.started += instance.OnRightHandPose;
                @rightHandPose.performed += instance.OnRightHandPose;
                @rightHandPose.canceled += instance.OnRightHandPose;
                @leftHandPose.started += instance.OnLeftHandPose;
                @leftHandPose.performed += instance.OnLeftHandPose;
                @leftHandPose.canceled += instance.OnLeftHandPose;
            }
        }
    }
    public VrControlsActions @vrControls => new VrControlsActions(this);
    public interface IDesktopActions
    {
        void OnA(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnC(InputAction.CallbackContext context);
        void OnD(InputAction.CallbackContext context);
        void OnE(InputAction.CallbackContext context);
        void OnF(InputAction.CallbackContext context);
        void OnG(InputAction.CallbackContext context);
        void OnH(InputAction.CallbackContext context);
        void OnI(InputAction.CallbackContext context);
        void OnJ(InputAction.CallbackContext context);
        void OnK(InputAction.CallbackContext context);
        void OnL(InputAction.CallbackContext context);
        void OnM(InputAction.CallbackContext context);
        void OnN(InputAction.CallbackContext context);
        void OnO(InputAction.CallbackContext context);
        void OnP(InputAction.CallbackContext context);
        void OnQ(InputAction.CallbackContext context);
        void OnR(InputAction.CallbackContext context);
        void OnS(InputAction.CallbackContext context);
        void OnT(InputAction.CallbackContext context);
        void OnU(InputAction.CallbackContext context);
        void OnV(InputAction.CallbackContext context);
        void OnW(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnZ(InputAction.CallbackContext context);
        void OnTab(InputAction.CallbackContext context);
        void OnRightMouse(InputAction.CallbackContext context);
        void OnMiddleMouse(InputAction.CallbackContext context);
        void OnLeftMouse(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMouseVelocity(InputAction.CallbackContext context);
        void OnLeftShift(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
        void OnSpace(InputAction.CallbackContext context);
        void OnEsc(InputAction.CallbackContext context);
        void OnLeftControl(InputAction.CallbackContext context);
    }
    public interface IVrControlsActions
    {
        void OnLeftAnalogPos(InputAction.CallbackContext context);
        void OnRightAnalogPos(InputAction.CallbackContext context);
        void OnLeftTrigger(InputAction.CallbackContext context);
        void OnRightTrigger(InputAction.CallbackContext context);
        void OnCenterEyePos(InputAction.CallbackContext context);
        void OnCenterEyeRot(InputAction.CallbackContext context);
        void OnRightHandPos(InputAction.CallbackContext context);
        void OnRightHandRot(InputAction.CallbackContext context);
        void OnLeftHandPos(InputAction.CallbackContext context);
        void OnLeftHandRot(InputAction.CallbackContext context);
        void OnLeftTriggerClick(InputAction.CallbackContext context);
        void OnRightTriggerClick(InputAction.CallbackContext context);
        void OnRightButtonA(InputAction.CallbackContext context);
        void OnLeftButtonA(InputAction.CallbackContext context);
        void OnRightButtonB(InputAction.CallbackContext context);
        void OnLeftButtonB(InputAction.CallbackContext context);
        void OnRightGrip(InputAction.CallbackContext context);
        void OnLeftGrip(InputAction.CallbackContext context);
        void OnRightHandPose(InputAction.CallbackContext context);
        void OnLeftHandPose(InputAction.CallbackContext context);
    }
}
