//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_player_grab;
        
        private static SteamVR_Action_Boolean p_player_action;
        
        private static SteamVR_Action_Boolean p_player_trackpadpress;
        
        private static SteamVR_Action_Vector2 p_player_trackpad;
        
        private static SteamVR_Action_Boolean p_player_pause;
        
        private static SteamVR_Action_Pose p_player_pose;
        
        public static SteamVR_Action_Boolean player_grab
        {
            get
            {
                return SteamVR_Actions.p_player_grab.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean player_action
        {
            get
            {
                return SteamVR_Actions.p_player_action.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean player_trackpadpress
        {
            get
            {
                return SteamVR_Actions.p_player_trackpadpress.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 player_trackpad
        {
            get
            {
                return SteamVR_Actions.p_player_trackpad.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean player_pause
        {
            get
            {
                return SteamVR_Actions.p_player_pause.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose player_pose
        {
            get
            {
                return SteamVR_Actions.p_player_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.player_grab,
                    SteamVR_Actions.player_action,
                    SteamVR_Actions.player_trackpadpress,
                    SteamVR_Actions.player_trackpad,
                    SteamVR_Actions.player_pause,
                    SteamVR_Actions.player_pose};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.player_grab,
                    SteamVR_Actions.player_action,
                    SteamVR_Actions.player_trackpadpress,
                    SteamVR_Actions.player_trackpad,
                    SteamVR_Actions.player_pause,
                    SteamVR_Actions.player_pose};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.player_pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.player_grab,
                    SteamVR_Actions.player_action,
                    SteamVR_Actions.player_trackpadpress,
                    SteamVR_Actions.player_pause};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.player_trackpad};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.player_grab,
                    SteamVR_Actions.player_action,
                    SteamVR_Actions.player_trackpadpress,
                    SteamVR_Actions.player_trackpad,
                    SteamVR_Actions.player_pause};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_player_grab = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/player/in/grab")));
            SteamVR_Actions.p_player_action = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/player/in/action")));
            SteamVR_Actions.p_player_trackpadpress = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/player/in/trackpadpress")));
            SteamVR_Actions.p_player_trackpad = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/player/in/trackpad")));
            SteamVR_Actions.p_player_pause = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/player/in/pause")));
            SteamVR_Actions.p_player_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/player/in/pose")));
        }
    }
}
