{
    "qualityLevel": 2,
    "shadowLevel": 3,
    "aliasingLevel": 1,
    "bakeNavJobs": 2,
    "musicVolume": 1.0,
    "commonCharacterScripts": [
        "headpat",
        "pickup",
        "idling",
        "follow",
        "handhold",
        "balance",
        "sleep",
        "poke",
        "wave",
        "recipes",
        "slideDoors",
        "hug",
        "snack",
        "give",
        "ball"
    ]
}