//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_player : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean grab
        {
            get
            {
                return SteamVR_Actions.player_grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean action
        {
            get
            {
                return SteamVR_Actions.player_action;
            }
        }
        
        public virtual SteamVR_Action_Boolean trackpadpress
        {
            get
            {
                return SteamVR_Actions.player_trackpadpress;
            }
        }
        
        public virtual SteamVR_Action_Vector2 trackpad
        {
            get
            {
                return SteamVR_Actions.player_trackpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean pause
        {
            get
            {
                return SteamVR_Actions.player_pause;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.player_pose;
            }
        }
    }
}
